FROM containers.intersystems.com/intersystems/iris-community:latest

RUN --mount=type=bind,src=.,dst=/home/irisowner/irislab <<EOT
iris start iris
cat <<"EOF" | iris session iris -U %SYS
do $system.OBJ.Load("/tmp/zpm.xml", "ck")
Do ##class(Security.Users).UnExpireUserPasswords("*")
zpm "load /home/irisowner/dev -v"
halt
EOF
iris stop iris quietly
EOT