services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      - H=source_id bp_min_flux bp_max_flux rp_min_flux rp_max_flux percentage_change
      - "Z=zcat /i/*|grep ^[0-9]"
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
      - ./data/in:/i:ro
      - ./data/out:/o
